#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: peer_tutor_development
  pool: 5
  username:  ##Username belongs here
  password:  ##Password belongs here

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: peer_tutor_development
  pool: 5 #default
  username:  ##Same username in line 12
  password:  ##Same password in line 13
